"""Auditable audio/video acquisition, decoding, and visual analysis."""

from gaia_max.media.asr import (
    ASREngine,
    ASRPass,
    DisputedSegment,
    FasterWhisperEngine,
    Transcript,
    TranscriptSegment,
    reconcile_transcripts,
    transcribe_timestamped,
)
from gaia_max.media.audio_tasks import (
    IngredientResult,
    NumericPageResult,
    extract_ingredients,
    extract_numeric_pages,
)
from gaia_max.media.core import (
    DerivedMedia,
    MediaProbe,
    MediaProcessingError,
    MediaStream,
    normalize_audio,
    probe_media,
)
from gaia_max.media.video import (
    BoundingRegion,
    FrameArtifact,
    FrameSpeciesObservation,
    SpeciesDetection,
    SpeciesMaximum,
    build_contact_sheet,
    extract_frames,
    frame_sample_times,
    reconcile_species_maximum,
)
from gaia_max.media.youtube import (
    CaptionCue,
    CaptionTrack,
    ExactSpeechAnswer,
    YouTubeEvidence,
    YtDlpClient,
    acquire_youtube_evidence,
    parse_webvtt,
    parse_youtube_video_id,
    solve_exact_youtube_speech,
)

__all__ = [
    "ASREngine",
    "ASRPass",
    "BoundingRegion",
    "CaptionCue",
    "CaptionTrack",
    "DerivedMedia",
    "DisputedSegment",
    "ExactSpeechAnswer",
    "FasterWhisperEngine",
    "FrameArtifact",
    "FrameSpeciesObservation",
    "IngredientResult",
    "MediaProbe",
    "MediaProcessingError",
    "MediaStream",
    "NumericPageResult",
    "SpeciesDetection",
    "SpeciesMaximum",
    "Transcript",
    "TranscriptSegment",
    "YouTubeEvidence",
    "YtDlpClient",
    "acquire_youtube_evidence",
    "build_contact_sheet",
    "extract_frames",
    "extract_ingredients",
    "extract_numeric_pages",
    "frame_sample_times",
    "normalize_audio",
    "parse_webvtt",
    "parse_youtube_video_id",
    "probe_media",
    "reconcile_species_maximum",
    "reconcile_transcripts",
    "solve_exact_youtube_speech",
    "transcribe_timestamped",
]
